uwsgi:
  app_id: sample
  module: apps.sample.app:dispatch
  hostname: sample.amp.sh
  chdir: /ampush/apps/sample/app
  include: /ampush/platform/conf/uwsgi/vassal.ini
  include: /ampush/platform/conf/uwsgi/runtime/python.ini
