#!/bin/bash

## Generates autobuilt-files for Hermes.

VERSION="0.1"
TRACK="alpha"
BUILD="00"

RELEASE="$VERSION-$BUILD-$TRACK"

echo "";
echo "";
echo "========= Hermes: Compilation Routine =========";
echo "";
echo "--- Building application JS...";
echo "";
echo "--- Building application SASS...";
echo "";
echo "--- Building application docs...";
PYTHONPATH="app:app/lib:app/lib/dist:/appengine:/appengine/lib" sphinx-apidoc -o docs/source/app -l -H "Sample" -A "Ampush" -V "$VERSION" -R "$RELEASE" -d 3 ./app;
PYTHONPATH="app:app/lib:app/lib/dist:/appengine:/appengine/lib" sphinx-build -b html docs/source/app docs/html/app;
echo "";
echo "--- Building API client libraries...";
echo "";
echo "(building Python bindings)...";
PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="/appengine:/appengine/lib:app:app/lib:app/lib/dist" python tools/gen_protorpc.py registry localhost:8080 /_api/rpc/system /_api/registry -d tools/client -f;
echo "";
echo "(building JS bindings)...";
echo "";
echo "(building Protobuf bindings)...";
echo ""
echo "Building API docs...";
PYTHONPATH="app:tools:app/lib:app/lib/dist:/appengine:/appengine/lib" sphinx-apidoc -o docs/source/api -l --full -H "Hermes API" -A "Ampush" -V "$VERSION" -R "$RELEASE" -d 2 ./tools/client;
PYTHONPATH="app:tools:app/lib:app/lib/dist:/appengine:/appengine/lib" sphinx-build -b html docs/source/api docs/html/api;
echo "";
echo "========= Compilation succeeded. =========";
echo "";
echo "";
